apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    deploymentconfig: postgres-db
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
      - image: postgres:9.4
        imagePullPolicy: Always
        name: postgres-db
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume
        env:
         - name: POSTGRES_PASSWORD
           value: "postgres"
         - name: POSTGRES_USER
           value: "postgres"
         - name: POSTGRES_HOST_AUTH_METHOD
           value: trust
      volumes:
      - emptyDir: {}
        name: postgres-db-volume
  test: false
  triggers:
  - type: ConfigChange
